[profile.default]
auto_detect_solc = true
optimizer = true
optimizer_runs = 1_000_000

solc = '0.8.26'
evm_version = "paris"

src = "src/"
test = "test/"
out = "foundry-artifacts"
cache_path = "foundry-cache"
libs = ['./node_modules', './lib']

bytecode_hash = "none"
ffi = false
via_ir = true

[rpc_endpoints]
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
base-sepolia = "https://base-sepolia-rpc.publicnode.com"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
base-sepolia = { key = "${ETHERSCAN_API_KEY}" }
